name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
    - name: Build ConfigAdapter
      run: dotnet build ConfigAdapter/ConfigAdapter.csproj
    - name: Build ConfigAdapter.Xml
      run: dotnet build ConfigAdapter.Xml/ConfigAdapter.Xml.csproj
    - name: Build ConfigAdapter.Ini
      run: dotnet build ConfigAdapter.Ini/ConfigAdapter.Ini.csproj
    - name: Build ConfigAdapter.HJson
      run: dotnet build ConfigAdapter.HJson/ConfigAdapter.HJson.csproj
    - name: Build test project
      run: dotnet build ConfigAdapter.Test/ConfigAdapter.Test.csproj
    - name: Run unit tests
      run: dotnet test ConfigAdapter.Test/ConfigAdapter.Test.csproj
